export default {
    // react routes
    main: '/',
    dashboard:'/dashboard',
    dashboardHomePage: '/dashboard/home',
    dashboardProductsPage: '/dashboard/products',
    dashboardSearchPage: '/dashboard/monograph',
    dashboardSearchPageMono: '/dashboard/monograph/:monoID',
    dashboardAccountPage: '/dashboard/account',
    dashboardAccountProviderInfo: '/dashboard/account/provider-info',
    dashboardAccountProfInfo: '/dashboard/account/prof-info',
    dashboardAccountPatientInfo: '/dashboard/account',
    dashboardQuickOrderPage: '/dashboard/quick-order',
    dashboardPatientsPage: '/dashboard/patients',
    dashboardBasketPage: '/dashboard/basket',
    dashboardCheckoutPage: '/dashboard/checkout',
    providerProductsBasket: '/dashboard/products/basket',
    dashboardHandoutPage: '/dashboard/handouts',
    forgotPasswordPage: '/forgot-password',   
    dashboardPatientPayment:'/dashboard/payments',
    dashboardProductDetails:'/dashboard/dashboardProductDetails',
    dashboardFAQ:'/dashboard/dashboardFAQ',
    dashboardDocumentInfo:'/documents',
    landingInfo: '/info',
    landingSignupPage: '/signup',
    landingSignupPatient: '/signup/patient',
    landingSignupPatientVerify: '/signup/patient/verify',
    landingSignupPatientRegistration: '/signup/patient/registration',
    landingSignupProvider: '/signup/provider',
    landingSignupProviderContacts: '/signup/provider/contacts',
    landingSignupProviderBusiness: '/signup/provider/business',
    LandingSignupProviderAgreement: '/signup/provider/agreement',
    LandingSignupProviderSalesPolicy: '/signup/provider/sales-policy',
    LandingSignupProviderReturnPolicy: '/signup/provider/return-policy',
    landingSignupProviderPayment: '/signup/provider/payment',
    landingSignupProviderGratitude: '/signup/provider/gratitude',
    orderViewPage:'/orderDetails'

};